// src/components/Organizations.tsx
"use client";

import { useRef, useCallback } from "react";
import { motion, useMotionValue, useSpring, useTransform } from "framer-motion";
import { ExternalLink, Users, Globe } from "lucide-react";

type Org = { name: string; role: string; description: string; url: string; logo: string; accentColor: string; members?: string; type: string; bgPattern: string; };

const organizations: Org[] = [
  { name: "CODE",  role: "Creative Team Member", description: "Coding Organization for Digital Excellence at Mapúa MCM. Contributing to community tech events, workshops, and collaborative software projects for students.",       url: "https://mapua.edu.ph", logo: "CODE", accentColor: "#38bdf8", type: "Student Org", bgPattern: "radial-gradient(circle at 80% 20%, rgba(56,189,248,0.12) 0%, transparent 60%)" },
  { name: "API",   role: "Creative Team Member", description: "Association of Proactive Innovators at Mapúa MCM. Driving innovation through hackathons, design sprints, and interdisciplinary projects that bridge tech and creativity.", url: "https://mapua.edu.ph", logo: "API",  accentColor: "#a78bfa", type: "Student Org", bgPattern: "radial-gradient(circle at 80% 20%, rgba(167,139,250,0.12) 0%, transparent 60%)" },
];

/* ─── Pulse ring component ────────────────────────── */
function PulseRings({ color }: { color: string }) {
  return (
    <div className="absolute -inset-2 pointer-events-none">
      {[0, 0.5, 1].map(delay => (
        <motion.div key={delay}
          className="absolute inset-0 rounded-full border"
          style={{ borderColor: `${color}40` }}
          animate={{ scale: [1, 1.6, 2], opacity: [0.5, 0.2, 0] }}
          transition={{ duration: 2.5, repeat: Infinity, delay, ease: "easeOut" }} />
      ))}
    </div>
  );
}

/* ─── Tilt card ───────────────────────────────────── */
function OrgCard({ org, i }: { org: Org; i: number }) {
  const ref = useRef<HTMLDivElement>(null);
  const mx = useMotionValue(0);
  const my = useMotionValue(0);
  const rx = useSpring(useTransform(my, [-0.5, 0.5], [6, -6]), { stiffness: 200, damping: 20 });
  const ry = useSpring(useTransform(mx, [-0.5, 0.5], [-6, 6]), { stiffness: 200, damping: 20 });

  const onMove = useCallback((e: React.MouseEvent) => {
    if (!ref.current) return;
    const r = ref.current.getBoundingClientRect();
    mx.set((e.clientX - r.left) / r.width - 0.5);
    my.set((e.clientY - r.top) / r.height - 0.5);
  }, [mx, my]);
  const onLeave = useCallback(() => { mx.set(0); my.set(0); }, [mx, my]);

  return (
    <motion.div
      initial={{ opacity: 0, y: 32 }} whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }} transition={{ delay: i * 0.12, duration: 0.5 }}>
      <motion.div ref={ref} onMouseMove={onMove} onMouseLeave={onLeave}
        style={{ rotateX: rx, rotateY: ry, transformStyle: "preserve-3d" }}
        whileHover={{ y: -6 }}
        className="glass shimmer-card relative p-6 flex flex-col gap-5 cursor-default overflow-hidden h-full"
        transition={{ duration: 0.3 }}>

        {/* BG pattern */}
        <div className="absolute inset-0 rounded-[18px] pointer-events-none" style={{ background: org.bgPattern }} />

        {/* Animated top line */}
        <motion.div className="absolute top-0 left-0 right-0 h-[2px] rounded-t-[18px]"
          style={{ background: `linear-gradient(90deg, transparent, ${org.accentColor}, transparent)` }}
          animate={{ opacity: [0.5, 1, 0.5] }} transition={{ duration: 2 + i * 0.4, repeat: Infinity }} />

        {/* Logo + info */}
        <div className="flex items-start justify-between relative z-10">
          <div className="flex items-center gap-4">
            {/* Logo with pulse */}
            <div className="relative shrink-0">
              <motion.div
                className="w-12 h-12 rounded-xl flex items-center justify-center text-xs font-bold"
                style={{ background: `${org.accentColor}18`, border: `1px solid ${org.accentColor}40`, color: org.accentColor, fontFamily: "'Space Grotesk',sans-serif" }}
                whileHover={{ scale: 1.15, boxShadow: `0 0 20px ${org.accentColor}60` }}
                animate={{ boxShadow: [`0 0 0px ${org.accentColor}00`, `0 0 14px ${org.accentColor}50`, `0 0 0px ${org.accentColor}00`] }}
                transition={{ duration: 3 + i * 0.5, repeat: Infinity }}>
                {org.logo}
              </motion.div>
              <PulseRings color={org.accentColor} />
            </div>

            <div>
              <h3 className="font-semibold text-base" style={{ color: "var(--text-primary)", fontFamily: "'Space Grotesk',sans-serif" }}>{org.name}</h3>
              <p className="text-xs mt-0.5" style={{ color: "var(--text-muted)" }}>{org.role}</p>
            </div>
          </div>

          <motion.a href={org.url} target="_blank" rel="noopener noreferrer"
            whileHover={{ scale: 1.15, rotate: -5 }} whileTap={{ scale: 0.9 }}
            className="p-2 rounded-lg cursor-pointer transition-colors"
            style={{ color: "var(--text-muted)", background: "rgba(255,255,255,0.05)" }}
            onMouseEnter={e => (e.currentTarget.style.color = org.accentColor)}
            onMouseLeave={e => (e.currentTarget.style.color = "var(--text-muted)")}
            aria-label={`Visit ${org.name}`}>
            <ExternalLink size={14} />
          </motion.a>
        </div>

        <p className="text-sm leading-relaxed relative z-10" style={{ color: "var(--text-secondary)" }}>{org.description}</p>

        <div className="flex items-center gap-3 pt-3 relative z-10" style={{ borderTop: "1px solid rgba(255,255,255,0.07)" }}>
          <span className="flex items-center gap-1.5 text-xs px-3 py-1 rounded-full"
            style={{ background: `${org.accentColor}12`, border: `1px solid ${org.accentColor}28`, color: org.accentColor }}>
            <Globe size={10} />
            {org.type}
          </span>
          {org.members && (
            <span className="text-xs flex items-center gap-1" style={{ color: "var(--text-muted)" }}>
              <Users size={11} /> {org.members} members
            </span>
          )}
        </div>
      </motion.div>
    </motion.div>
  );
}

export default function Organizations() {
  return (
    <section id="organizations" className="py-28 relative overflow-hidden">

      <div className="relative z-10 max-w-6xl mx-auto px-6">
        <motion.div initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-16">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-8 h-px" style={{ background: "linear-gradient(90deg,var(--accent-cyan),var(--accent-green))" }} />
            <p className="text-xs font-semibold tracking-[0.2em] uppercase" style={{ color: "var(--accent-cyan)" }}>Community</p>
          </div>
          <h2 className="text-4xl md:text-5xl font-bold" style={{ color: "var(--text-primary)" }}>
            <span className="gradient-text-green-cyan">Organizations</span>
          </h2>
        </motion.div>

        <div className="grid md:grid-cols-2 gap-5">
          {organizations.map((org, i) => <OrgCard key={org.name} org={org} i={i} />)}
        </div>
      </div>
    </section>
  );
}

// src/components/sections/Organizations.vue
<script setup lang="ts">
import { ExternalLink, Globe } from '@lucide/vue'
import { organizations } from '@/data/organizations'
</script>

<template>
  <section id="organizations" class="relative py-24 md:py-32 overflow-hidden">
    <div class="relative z-10 max-w-6xl mx-auto px-6">
      <!-- Header -->
      <div v-reveal class="mb-16">
        <div class="flex items-center gap-3 mb-3">
          <span class="w-8" style="height: 3px; background: linear-gradient(90deg, var(--accent-cyan), var(--accent-green))" />
          <p class="text-[10px] font-mono tracking-[0.3em] uppercase" style="color: var(--accent-cyan)">// Community</p>
        </div>
        <h2 class="text-2xl md:text-4xl gradient-text-green-cyan">ORGANIZATIONS</h2>
      </div>

      <div class="grid md:grid-cols-2 gap-5">
        <div
          v-for="(org, i) in organizations"
          :key="org.name"
          v-scrub="{ y: i === 0 ? [50, -50] : [-50, 50] }"
          class="h-full"
        >
        <article
          v-tilt="6"
          class="panel shimmer-card relative p-6 flex flex-col gap-5 h-full overflow-hidden"
        >
          <div class="absolute inset-0 pointer-events-none" :style="{ background: org.bgPattern }" />
          <span
            class="absolute top-0 left-0 right-0"
            :style="{ height: '3px', background: `linear-gradient(90deg, transparent, ${org.accentColor}, transparent)` }"
          />

          <div class="flex items-start justify-between relative z-10">
            <div class="flex items-center gap-4">
              <div
                class="org-logo w-12 h-12 flex items-center justify-center text-[10px]"
                :style="{ background: org.accentColor + '1f', border: `2px solid ${org.accentColor}40`, color: org.accentColor, fontFamily: 'var(--font-display)' }"
              >
                {{ org.logo }}
              </div>
              <div>
                <h3 class="text-sm" style="color: var(--text-primary); font-family: var(--font-display)">{{ org.name }}</h3>
                <p class="text-[11px] font-mono mt-1" style="color: var(--text-muted)">{{ org.role }}</p>
              </div>
            </div>
            <a
              :href="org.url"
              target="_blank"
              rel="noopener noreferrer"
              class="p-2 cursor-pointer transition-transform hover:scale-110 text-[var(--text-muted)]"
              style="background: rgba(255,255,255,0.05)"
              :aria-label="`Visit ${org.name}`"
              @mouseenter="(e) => ((e.currentTarget as HTMLElement).style.color = org.accentColor)"
              @mouseleave="(e) => ((e.currentTarget as HTMLElement).style.color = 'var(--text-muted)')"
            >
              <ExternalLink :size="14" />
            </a>
          </div>

          <p class="text-sm leading-relaxed relative z-10" style="color: var(--text-secondary)">{{ org.description }}</p>

          <div class="flex items-center gap-3 pt-3 relative z-10" style="border-top: 2px solid rgba(255,255,255,0.07)">
            <span
              class="flex items-center gap-1.5 text-[11px] font-mono px-3 py-1"
              :style="{ background: org.accentColor + '14', border: `2px solid ${org.accentColor}28`, color: org.accentColor }"
            >
              <Globe :size="10" />
              {{ org.type }}
            </span>
          </div>
        </article>
        </div>
      </div>
    </div>
  </section>
</template>

<style scoped>
.org-logo {
  animation: pulse-glow 3s ease-in-out infinite;
}
</style>
