// src/components/layout/Navbar.vue
<script setup lang="ts">
import { onMounted, onBeforeUnmount, ref } from 'vue'
import { Menu, X } from '@lucide/vue'
import { navLinks } from '@/data/nav'
import { profile } from '@/data/profile'

const scrolled = ref(false)
const mobileOpen = ref(false)
const active = ref('')

let observer: IntersectionObserver | null = null
const onScroll = () => {
  scrolled.value = window.scrollY > 20
}

onMounted(() => {
  window.addEventListener('scroll', onScroll, { passive: true })
  observer = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) active.value = entry.target.id
      })
    },
    { threshold: 0.4 },
  )
  navLinks.forEach(({ href }) => {
    const el = document.querySelector(href)
    if (el) observer?.observe(el)
  })
})

onBeforeUnmount(() => {
  window.removeEventListener('scroll', onScroll)
  observer?.disconnect()
})
</script>

<template>
  <nav
    class="fixed top-0 left-0 right-0 z-50 transition-all duration-300"
    :class="scrolled ? 'glass-navbar' : 'bg-transparent'"
    :style="
      scrolled
        ? 'background:rgba(5,3,10,0.85);backdrop-filter:blur(12px);border-bottom:2px solid rgba(167,139,250,0.25);box-shadow:0 4px 0 rgba(0,0,0,0.4)'
        : ''
    "
  >
    <div class="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
      <!-- Brand -->
      <a
        href="#"
        class="text-sm cursor-pointer select-none gradient-text-cyan-violet text-glow-violet"
        style="font-family: var(--font-display)"
      >
        {{ profile.brand }}
      </a>

      <!-- Desktop links -->
      <ul class="hidden md:flex items-center gap-1">
        <li v-for="link in navLinks" :key="link.href">
          <a
            :href="link.href"
            class="relative px-3 py-2 text-xs font-mono uppercase tracking-wider rounded-none transition-colors duration-200 cursor-pointer"
            :class="
              active === link.href.replace('#', '')
                ? 'text-[var(--accent-violet)]'
                : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)]'
            "
          >
            <span
              v-if="active === link.href.replace('#', '')"
              class="absolute inset-0 -z-10"
              style="background: rgba(167,139,250,0.12); border: 2px solid rgba(167,139,250,0.3)"
            />
            <span class="relative">{{ link.label }}</span>
          </a>
        </li>
      </ul>

      <!-- CTA -->
      <a
        :href="`mailto:${profile.email}`"
        class="hidden md:flex items-center gap-2 px-4 py-2 text-xs font-mono uppercase tracking-wider cursor-pointer transition-all duration-200 hover:-translate-y-0.5"
        style="
          background: linear-gradient(135deg, rgba(56,189,248,0.18), rgba(167,139,250,0.18));
          border: 2px solid rgba(120,140,255,0.4);
          color: #f0f4ff;
        "
      >
        Hire Me
      </a>

      <!-- Mobile toggle -->
      <button
        class="md:hidden p-2 text-[var(--text-secondary)] hover:text-[var(--text-primary)] cursor-pointer transition-colors"
        aria-label="Toggle menu"
        @click="mobileOpen = !mobileOpen"
      >
        <X v-if="mobileOpen" :size="20" />
        <Menu v-else :size="20" />
      </button>
    </div>

    <!-- Mobile menu -->
    <Transition name="fade-down">
      <div
        v-if="mobileOpen"
        class="md:hidden"
        style="background: rgba(5,3,10,0.94); backdrop-filter: blur(12px); border-bottom: 2px solid rgba(167,139,250,0.2)"
      >
        <ul class="max-w-6xl mx-auto px-6 py-4 flex flex-col gap-1">
          <li v-for="link in navLinks" :key="link.href">
            <a
              :href="link.href"
              class="block px-4 py-3 text-sm font-mono uppercase tracking-wider text-[var(--text-secondary)] hover:text-[var(--accent-violet)] cursor-pointer transition-colors"
              @click="mobileOpen = false"
            >
              {{ link.label }}
            </a>
          </li>
        </ul>
      </div>
    </Transition>
  </nav>
</template>

<style scoped>
.fade-down-enter-active,
.fade-down-leave-active {
  transition: opacity 0.2s ease, transform 0.2s ease;
}
.fade-down-enter-from,
.fade-down-leave-to {
  opacity: 0;
  transform: translateY(-10px);
}
</style>

// src/components/Navbar.tsx
"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Menu, X } from "lucide-react";

const navLinks = [
  { label: "About", href: "#about" },
  { label: "Projects", href: "#projects" },
  { label: "GitHub", href: "#github" },
  { label: "Orgs", href: "#organizations" },
  { label: "Certs", href: "#certifications" },
];

export default function Navbar() {
  const [scrolled, setScrolled] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [active, setActive] = useState("");

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 20);
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) setActive(entry.target.id);
        });
      },
      { threshold: 0.4 }
    );
    navLinks.forEach(({ href }) => {
      const el = document.querySelector(href);
      if (el) observer.observe(el);
    });
    return () => observer.disconnect();
  }, []);

  return (
    <>
      <motion.nav
        initial={{ y: -100, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ duration: 0.7, ease: "easeOut" }}
        className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
          scrolled ? "glass-navbar shadow-lg shadow-black/40" : "bg-transparent"
        }`}
      >
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          {/* Logo */}
          <motion.a
            href="#"
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            className="font-bold text-xl cursor-pointer select-none"
            style={{ fontFamily: "'Space Grotesk', sans-serif" }}
          >
            <span className="gradient-text-cyan-violet">&lt;Dev/&gt;</span>
          </motion.a>

          {/* Desktop Links */}
          <ul className="hidden md:flex items-center gap-1">
            {navLinks.map(({ label, href }) => {
              const id = href.replace("#", "");
              const isActive = active === id;
              return (
                <li key={href}>
                  <motion.a
                    href={href}
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}
                    className={`relative px-4 py-2 text-sm font-medium rounded-lg transition-all duration-200 cursor-pointer ${
                      isActive
                        ? "text-[#a78bfa]"
                        : "text-[#b8c4e8] hover:text-[#f0f4ff]"
                    }`}
                  >
                    {isActive && (
                      <motion.span
                        layoutId="nav-pill"
                        className="absolute inset-0 rounded-lg"
                        style={{
                          background: "rgba(167,139,250,0.1)",
                          border: "1px solid rgba(167,139,250,0.25)",
                        }}
                        transition={{ type: "spring", bounce: 0.25, duration: 0.4 }}
                      />
                    )}
                    <span className="relative z-10">{label}</span>
                  </motion.a>
                </li>
              );
            })}
          </ul>

          {/* CTA */}
          <motion.a
            href="mailto:you@example.com"
            whileHover={{
              scale: 1.05,
              boxShadow: "0 0 22px rgba(56,189,248,0.45)",
            }}
            whileTap={{ scale: 0.95 }}
            className="hidden md:flex items-center gap-2 px-4 py-2 text-sm font-semibold rounded-lg cursor-pointer transition-all duration-200"
            style={{
              background: "linear-gradient(135deg, rgba(56,189,248,0.15), rgba(167,139,250,0.15))",
              border: "1px solid rgba(120,140,255,0.3)",
              color: "#f0f4ff",
            }}
          >
            Hire Me
          </motion.a>

          {/* Mobile Toggle */}
          <button
            onClick={() => setMobileOpen(!mobileOpen)}
            className="md:hidden p-2 text-[#b8c4e8] hover:text-[#f0f4ff] cursor-pointer transition-colors"
            aria-label="Toggle menu"
          >
            {mobileOpen ? <X size={20} /> : <Menu size={20} />}
          </button>
        </div>
      </motion.nav>

      {/* Mobile Menu */}
      <AnimatePresence>
        {mobileOpen && (
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            transition={{ duration: 0.2 }}
            className="fixed top-16 left-0 right-0 z-40 md:hidden"
            style={{
              background: "rgba(5,8,20,0.88)",
              backdropFilter: "blur(20px)",
              borderBottom: "1px solid rgba(120,140,255,0.1)",
            }}
          >
            <ul className="max-w-6xl mx-auto px-6 py-4 flex flex-col gap-1">
              {navLinks.map(({ label, href }, i) => (
                <motion.li
                  key={href}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: i * 0.05 }}
                >
                  <a
                    href={href}
                    onClick={() => setMobileOpen(false)}
                    className="block px-4 py-3 text-[#b8c4e8] hover:text-[#a78bfa] rounded-lg transition-colors duration-200 cursor-pointer text-sm"
                    style={{ borderRadius: 8 }}
                  >
                    {label}
                  </a>
                </motion.li>
              ))}
            </ul>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}
