// src/components/sections/Projects.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { ExternalLink, Star, Zap } from '@lucide/vue'
import { GithubIcon } from '@/components/icons/brand'
import { projects, categories } from '@/data/projects'
import { GITHUB_USERNAME } from '@/data/github'

const filter = ref<string>('All')
const filtered = computed(() =>
  filter.value === 'All' ? projects : projects.filter((p) => p.category === filter.value),
)
</script>

<template>
  <section id="projects" class="relative py-24 md:py-32 overflow-hidden">
    <div class="relative z-10 max-w-6xl mx-auto px-6">
      <!-- Header -->
      <div v-reveal class="mb-12">
        <div class="flex items-center gap-3 mb-3">
          <span class="w-8" style="height: 3px; background: linear-gradient(90deg, var(--accent-violet), var(--accent-pink))" />
          <p class="text-[10px] font-mono tracking-[0.3em] uppercase" style="color: var(--accent-violet)">// Work</p>
        </div>
        <h2 class="text-2xl md:text-4xl" style="color: var(--text-primary)">
          FEATURED <span class="gradient-text-violet-pink">PROJECTS</span>
        </h2>
      </div>

      <!-- Filter -->
      <div class="flex flex-wrap gap-2 mb-10">
        <button
          v-for="cat in categories"
          :key="cat"
          class="px-4 py-1.5 text-[11px] font-mono uppercase tracking-wider cursor-pointer transition-all duration-150"
          :style="
            filter === cat
              ? 'background:linear-gradient(135deg,rgba(167,139,250,0.25),rgba(244,114,182,0.15));border:2px solid rgba(167,139,250,0.5);color:var(--accent-violet)'
              : 'background:rgba(18,26,70,0.7);border:2px solid rgba(255,255,255,0.08);color:var(--text-muted)'
          "
          @click="filter = cat"
        >
          {{ cat }}
        </button>
      </div>

      <!-- Grid -->
      <div v-scrub="{ y: [60, -30] }" class="grid md:grid-cols-2 lg:grid-cols-3 gap-5">
        <article
          v-for="p in filtered"
          :key="p.title"
          v-tilt="7"
          class="panel shimmer-card relative p-6 flex flex-col gap-4 h-full"
        >
          <!-- accent top bar -->
          <span
            class="absolute top-0 left-0 right-0"
            :style="{ height: '3px', background: `linear-gradient(90deg, transparent, ${p.accentColor}, transparent)` }"
          />

          <header class="flex items-start justify-between">
            <div class="flex items-center gap-3">
              <span class="text-2xl pixelated">{{ p.icon }}</span>
              <div>
                <h3 class="text-sm" style="color: var(--text-primary); font-family: var(--font-display)">{{ p.title }}</h3>
                <span
                  class="text-[10px] font-mono px-2 py-0.5 mt-1 inline-block"
                  :style="{ background: p.accentColor + '1f', border: `2px solid ${p.accentColor}35`, color: p.accentColor }"
                >{{ p.category }}</span>
              </div>
            </div>
            <span
              v-if="p.featured"
              class="flex items-center gap-1 text-[9px] font-mono px-2 py-0.5"
              style="background: rgba(167,139,250,0.12); border: 2px solid rgba(167,139,250,0.3); color: var(--accent-violet)"
            >
              <Zap :size="9" fill="currentColor" /> FEAT
            </span>
          </header>

          <p class="text-sm leading-relaxed flex-1" style="color: var(--text-secondary)">{{ p.description }}</p>

          <div class="flex flex-wrap gap-1.5">
            <span
              v-for="tag in p.tags"
              :key="tag"
              class="text-[10px] font-mono px-2.5 py-0.5"
              style="background: rgba(120,140,255,0.08); border: 2px solid rgba(255,255,255,0.08); color: var(--text-muted)"
            >{{ tag }}</span>
          </div>

          <footer class="flex items-center justify-between pt-3" style="border-top: 2px solid rgba(255,255,255,0.07)">
            <div class="flex items-center gap-1.5 text-sm" style="color: var(--accent-amber)">
              <template v-if="p.stars > 0">
                <Star :size="13" fill="currentColor" />
                <span class="font-mono">{{ p.stars }}</span>
              </template>
            </div>
            <div class="flex items-center gap-1">
              <a
                :href="p.github"
                target="_blank"
                rel="noopener noreferrer"
                class="p-1.5 cursor-pointer transition-transform hover:scale-125 text-[var(--text-muted)]"
                :aria-label="`${p.title} on GitHub`"
                @mouseenter="(e) => ((e.currentTarget as HTMLElement).style.color = p.accentColor)"
                @mouseleave="(e) => ((e.currentTarget as HTMLElement).style.color = 'var(--text-muted)')"
              >
                <GithubIcon :size="15" />
              </a>
              <a
                v-if="p.live"
                :href="p.live"
                target="_blank"
                rel="noopener noreferrer"
                class="p-1.5 cursor-pointer transition-transform hover:scale-125 text-[var(--text-muted)]"
                aria-label="Live link"
                @mouseenter="(e) => ((e.currentTarget as HTMLElement).style.color = p.accentColor)"
                @mouseleave="(e) => ((e.currentTarget as HTMLElement).style.color = 'var(--text-muted)')"
              >
                <ExternalLink :size="15" />
              </a>
            </div>
          </footer>
        </article>
      </div>

      <div class="mt-10 flex justify-center">
        <a
          :href="`https://github.com/${GITHUB_USERNAME}`"
          target="_blank"
          rel="noopener noreferrer"
          class="panel shimmer-card inline-flex items-center gap-2 px-6 py-3 text-xs font-mono uppercase tracking-wider cursor-pointer transition-all duration-200 hover:-translate-y-1 text-[var(--text-secondary)] hover:text-[var(--accent-violet)]"
        >
          <GithubIcon :size="15" />
          View All Repositories
        </a>
      </div>
    </div>
  </section>
</template>

// src/components/Projects.tsx
"use client";

import { useState, useRef, useCallback } from "react";
import { motion, AnimatePresence, useMotionValue, useSpring, useTransform } from "framer-motion";
import { ExternalLink, Star, Zap } from "lucide-react";
import { GithubIcon } from "./icons";

type Project = {
  title: string; description: string; tags: string[];
  category: string; stars: number; github: string;
  live?: string; featured?: boolean; accentColor: string; icon: string;
};

const projects: Project[] = [
  { title: "CloudDeploy CLI",     description: "One-command deployments to AWS, GCP & Azure. Multi-env configs, rollback, real-time logs.",         tags: ["Go","AWS","Docker","CLI"],        category: "DevOps",   stars: 842,  github: "https://github.com", live: "https://example.com", featured: true, accentColor: "#4ade80", icon: "☁️" },
  { title: "OpenAuth",            description: "Lightweight extensible auth for Node.js — OAuth2, OIDC, magic links, zero vendor lock-in.",           tags: ["TypeScript","Node.js","OAuth2"],  category: "Library",  stars: 1203, github: "https://github.com", featured: true, accentColor: "#38bdf8", icon: "🔐" },
  { title: "DataGrid Pro",        description: "High-performance React table with virtual scrolling, inline editing, and CSV/Excel export.",          tags: ["React","TypeScript","Canvas"],   category: "Frontend", stars: 578,  github: "https://github.com", live: "https://example.com", featured: true, accentColor: "#a78bfa", icon: "📊" },
  { title: "PocketDB",            description: "Embedded type-safe SQLite ORM for TypeScript — migrations, relations, fluent query builder.",         tags: ["TypeScript","SQLite","ORM"],     category: "Library",  stars: 391,  github: "https://github.com", accentColor: "#f472b6", icon: "🗃️" },
  { title: "StreamKit",           description: "Real-time streaming infra — WebSocket, SSE, long-poll. Built for high-throughput scenarios.",         tags: ["Node.js","Redis","WebSocket"],   category: "Backend",  stars: 267,  github: "https://github.com", accentColor: "#fbbf24", icon: "⚡" },
  { title: "DesignSystem UI",     description: "Accessible component library with Radix primitives, Tailwind, full theming and dark mode.",           tags: ["React","Tailwind","Radix UI"],   category: "Frontend", stars: 445,  github: "https://github.com", live: "https://example.com", accentColor: "#38bdf8", icon: "🎨" },
];

const categories = ["All","Frontend","Backend","DevOps","Library"];

/* ─── 3-D tilt project card ──────────────────────── */
function ProjectCard({ project, i }: { project: Project; i: number }) {
  const ref = useRef<HTMLDivElement>(null);
  const mx = useMotionValue(0);
  const my = useMotionValue(0);
  const rx = useSpring(useTransform(my, [-0.5, 0.5], [10, -10]), { stiffness: 180, damping: 18 });
  const ry = useSpring(useTransform(mx, [-0.5, 0.5], [-10, 10]), { stiffness: 180, damping: 18 });
  const shineX = useTransform(mx, [-0.5, 0, 0.5], ["-30%", "50%", "130%"]);
  const shineO = useTransform(mx, [-0.5, -0.1, 0.1, 0.5], [0, 0.12, 0.12, 0]);

  const onMove = useCallback((e: React.MouseEvent) => {
    if (!ref.current) return;
    const r = ref.current.getBoundingClientRect();
    mx.set((e.clientX - r.left) / r.width - 0.5);
    my.set((e.clientY - r.top) / r.height - 0.5);
  }, [mx, my]);
  const onLeave = useCallback(() => { mx.set(0); my.set(0); }, [mx, my]);

  return (
    <motion.div
      layout
      initial={{ opacity: 0, y: 32, scale: 0.94 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      exit={{ opacity: 0, y: -24, scale: 0.94 }}
      transition={{ delay: i * 0.07, duration: 0.45 }}
    >
      <motion.div
        ref={ref}
        onMouseMove={onMove}
        onMouseLeave={onLeave}
        style={{ rotateX: rx, rotateY: ry, transformStyle: "preserve-3d" }}
        whileHover={{ y: -8 }}
        className="glass shimmer-card relative p-6 flex flex-col gap-4 cursor-default h-full overflow-hidden"
        transition={{ duration: 0.3 }}
      >
        {/* Moving shine */}
        <motion.div className="absolute inset-0 pointer-events-none rounded-[18px]"
          style={{ background: `linear-gradient(105deg, transparent 35%, white 50%, transparent 65%)`, x: shineX, opacity: shineO }} />

        {/* Accent glow top border */}
        <motion.div className="absolute top-0 left-0 right-0 h-[2px] rounded-t-[18px]"
          style={{ background: `linear-gradient(90deg, transparent, ${project.accentColor}, transparent)` }}
          animate={{ opacity: [0.4, 0.9, 0.4] }} transition={{ duration: 2.5 + i * 0.3, repeat: Infinity }} />

        {/* Header */}
        <div className="flex items-start justify-between">
          <div className="flex items-center gap-3">
            <span className="text-2xl">{project.icon}</span>
            <div>
              <h3 className="font-semibold text-base" style={{ color: "var(--text-primary)", fontFamily: "'Space Grotesk',sans-serif" }}>
                {project.title}
              </h3>
              <span className="text-xs px-2 py-0.5 rounded-full mt-1 inline-block"
                style={{ background: `${project.accentColor}18`, border: `1px solid ${project.accentColor}35`, color: project.accentColor }}>
                {project.category}
              </span>
            </div>
          </div>
          {project.featured && (
            <span className="flex items-center gap-1 text-[10px] font-medium px-2 py-0.5 rounded-full"
              style={{ background: "rgba(167,139,250,0.12)", border: "1px solid rgba(167,139,250,0.3)", color: "var(--accent-violet)" }}>
              <Zap size={9} fill="currentColor" /> Featured
            </span>
          )}
        </div>

        <p className="text-sm leading-relaxed flex-1" style={{ color: "var(--text-secondary)" }}>{project.description}</p>

        <div className="flex flex-wrap gap-1.5">
          {project.tags.map(tag => (
            <span key={tag} className="text-xs px-2.5 py-0.5 rounded-full"
              style={{ background: "rgba(120,140,255,0.08)", border: "1px solid rgba(255,255,255,0.08)", color: "var(--text-muted)" }}>
              {tag}
            </span>
          ))}
        </div>

        <div className="flex items-center justify-between pt-3" style={{ borderTop: "1px solid rgba(255,255,255,0.07)" }}>
          <div className="flex items-center gap-1.5 text-sm" style={{ color: "var(--accent-amber)" }}>
            <Star size={13} fill="currentColor" />
            <span className="font-medium">{project.stars.toLocaleString()}</span>
          </div>
          <div className="flex items-center gap-1">
            {[
              { href: project.github, Icon: GithubIcon, label: "GitHub" },
              ...(project.live ? [{ href: project.live, Icon: ExternalLink, label: "Live" }] : []),
            ].map(({ href, Icon, label }) => (
              <motion.a key={label} href={href} target="_blank" rel="noopener noreferrer"
                whileHover={{ scale: 1.2, color: project.accentColor }}
                whileTap={{ scale: 0.9 }}
                className="p-1.5 cursor-pointer transition-colors"
                style={{ color: "var(--text-muted)" }}
                onMouseEnter={e => (e.currentTarget.style.color = project.accentColor)}
                onMouseLeave={e => (e.currentTarget.style.color = "var(--text-muted)")}
                aria-label={label}>
                <Icon size={15} />
              </motion.a>
            ))}
          </div>
        </div>
      </motion.div>
    </motion.div>
  );
}

export default function Projects() {
  const [filter, setFilter] = useState("All");
  const filtered = filter === "All" ? projects : projects.filter(p => p.category === filter);

  return (
    <section id="projects" className="py-28 relative overflow-hidden">
      <div className="relative z-10 max-w-6xl mx-auto px-6">
        {/* Header */}
        <motion.div initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-12">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-8 h-px" style={{ background: "linear-gradient(90deg,var(--accent-violet),var(--accent-pink))" }} />
            <p className="text-xs font-semibold tracking-[0.2em] uppercase" style={{ color: "var(--accent-violet)" }}>Work</p>
          </div>
          <h2 className="text-4xl md:text-5xl font-bold" style={{ color: "var(--text-primary)" }}>
            Featured <span className="gradient-text-violet-pink">Projects</span>
          </h2>
        </motion.div>

        {/* Filter */}
        <motion.div initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }} transition={{ delay: 0.2 }}
          className="flex flex-wrap gap-2 mb-10">
          {categories.map(cat => (
            <motion.button key={cat} onClick={() => setFilter(cat)}
              whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}
              className="px-4 py-1.5 text-sm rounded-full transition-all duration-200 cursor-pointer"
              style={filter === cat
                ? { background: "linear-gradient(135deg,rgba(167,139,250,0.25),rgba(244,114,182,0.15))", border: "1px solid rgba(167,139,250,0.5)", color: "var(--accent-violet)", fontWeight: 600 }
                : { background: "rgba(18,26,70,0.7)", border: "1px solid rgba(255,255,255,0.08)", color: "var(--text-muted)", backdropFilter: "blur(16px)" }
              }>
              {cat}
            </motion.button>
          ))}
        </motion.div>

        <motion.div layout className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">
          <AnimatePresence mode="popLayout">
            {filtered.map((p, i) => <ProjectCard key={p.title} project={p} i={i} />)}
          </AnimatePresence>
        </motion.div>

        <motion.div initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }} transition={{ delay: 0.4 }}
          className="mt-10 flex justify-center">
          <motion.a href="https://github.com/yourusername" target="_blank" rel="noopener noreferrer"
            whileHover={{ scale: 1.05, boxShadow: "0 0 24px rgba(167,139,250,0.25)" }} whileTap={{ scale: 0.95 }}
            className="glass shimmer-card gradient-border inline-flex items-center gap-2 px-6 py-3 text-sm font-medium cursor-pointer"
            style={{ color: "var(--text-secondary)" }}
            onMouseEnter={e => (e.currentTarget.style.color = "var(--accent-violet)")}
            onMouseLeave={e => (e.currentTarget.style.color = "var(--text-secondary)")}>
            <GithubIcon size={15} />
            View All Repositories
          </motion.a>
        </motion.div>
      </div>
    </section>
  );
}
